const mongoose=require("mongoose")

const propertyDetail=new mongoose.Schema({
    propertyType:{
        type:String,
        default:"House"
    },
    price:{
        type:String
    },
    propertyAge:{
        type:String,
        default:"New"
    },
    description:{
        type:String
    },
    nagotable:{
        type:String,
        default:"yes"
    },
    ownership:{
        type:String,
        default:"yes"
    },
    approved:{
        type:String,
        default:"yes"
    },
    bankLoan:{
        type:String,
        default:"no"
    },
    length:{
        type:String
    },
    breath:{
        type:String
    },
    totalArea:{
        type:String
    },
    noOfBHK:{
        type:String
    },
    attached:{
        type:String
    },
    furnished:{
        type:String
    },
    lift:{
        type:String
    },
    facing:{
        type:String
    },
    areaUnit:{
        type:String
    },
    noOfFloor:{
        type:String
    },
    westernToilet:{
        type:String
    },
    carParking:{
        type:String
    },
    electricity:{
        type:String
    },
    name:{
        type:String
    },
    mobileNo:{
        type:String
    },
    postedBy:{
        type:String
    },
    saleType:{
        type:String
    },
    featuredPackage:{
        type:String
    },
    PPDpackage:{
        type:String
    },
    email:{
        type:String
    },
    area:{
        type:String
    },
    address:{
        type:String
    },
    latitude:{
        type:String
    },
    city:{
        type:String
    },
    pincode:{
        type:String
    },
    landmark:{
        type:String
    },
    longitude:{
        type:String
    }
})

const property=mongoose.model("propertys",propertyDetail)
module.exports=property


    

